# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Patterns Not Included
author: Steven Andrew Carter
description: Some Random Musings about Development
lang: en
timezone: UTC
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor

# Social media
twitter_username:
twitter_image:
facebook_app_id:
facebook_image:
google_analytics:

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

# Outputting
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layout: category_archives
  permalinks:
    category: /categories/:name/
theme: jekyll-theme-cayman